sudo: false
language: perl
before_script:
  - "git config --global user.email 'you@example.com'"
  - "git config --global user.name 'Your Name'"
install:
  - cpanm -nq --installdeps --with-develop --with-recommends .
perl:
  - "5.22"

