sudo: false
language: perl
addons:
  apt:
      packages: 
        - r-base

before_script:
  - "git config --global user.email 'you@example.com'"
  - "git config --global user.name 'Your Name'"
install:
  -  cpanm --quiet --installdeps --notest .
perl:
  - "5.22"
