requires 'Module::Install';
requires 'Modern::Perl';
requires 'Moo';
requires 'Bio::SeqIO';
requires 'Statistics::Basic';
requires 'Statistics::R';
requires 'List::MoreUtils';
requires 'namespace::clean';
requires 'Set::IntervalTree';
requires 'experimental';
requires 'autodie';
requires 'Getopt::Lucid';
requires 'local::lib';
requires 'Parallel::ForkManager';
requires 'Array::Utils'
requires 'Test::More'
