#!/usr/bin/env perl

use Modern::Perl '2015';
use experimental qw/signatures/;
use Pod::Usage;
use autodie;
use Parallel::ForkManager;
use Getopt::Lucid qw/:all/;

my @specs = (
    Param("outputDIR|o")->default();
    Param("contigs|c"),
    Param("refseqKO|r")->default("/export2/home/uesu/db/konr/"),
    Param("threads|t")->default(1),
    Param("prefix|p"),
    Switch("help|h")
);

my $opt = Getopt::Lucid->getopt( \@specs )->validate;
pod2usage(-verbose=>2) if $opt->get_help;
#$opt->validate({'requires' => ['', 'blastFile', 'output', 'megan']});

my $outputDir = $opt->get_outputDIR;
my $refseqProtDB = $opt->get_refseqKO;
my $MAX_PROCESSES = $opt->get_threads;

say "## Using $MAX_PROCESSES threads";
##################################################
#Begin
##################################################

say "## Blasting";
system "script/pAss.00.blast.pl --threads $MAX_PROCESSES --format 0 --kodb $refseqProtDB";

say "MEGAN aln";
system "script/pAss.01.blast.pl";

say "## Generating MSA";
my $pm = Parallel::ForkManager->new($MAX_PROCESSES);

#need to change this; this is hard coded
foreach my $ko (`ls out/pAss01/ | grep -v log`)
{
    $pm->start and next;
    chomp $ko;
    #the concatenation of refseqProDB with KO, should be frowned upon
    system "script/pAss.03.master.msa.pl -f $refseqProtDB/ko:$ko -m out/pAss01/$ko -o out/pAss03 -k $ko";
    say STDERR "Done Processing $ko";
    $pm->finish;
}
$pm->wait_all_children;

say "## MSA statistics";
my $pm2 = Parallel::ForkManager->new($MAX_PROCESSES);
foreach my $ko (`ls $outputDir/out/pAss03/ | grep -v temp | sed s/\.msa//g`)
{
    chomp $ko;
    $pm2->start and next;
    system "script/pAss.04.msa2group.pl --msa $outputDir/out/pAss03/$ko.msa --outputPrefix $outputDir/out/pAss04/$ko";
    $pm2->finish;
}
$pm2->wait_all_children;

#Documentation
=pod

=head1 NAME

    maxDiversity

=head1 DESCRIPTION

    Before running maxDiversity the following is required:

=over 4

=item Protein Reference Sequences

    Prokaryotic sequences only,  grouped by KOs (eg. K00001.fa, K00002.fa)

=item Contigs

    Contigs should be in found in a root directory separated by KO ids (NEWBLER)

    root/directory
    |-- K00001
    |   |-- 454AllContigs.fna
    |   |-- 454AllContigs.qual
    |   |-- 454ContigGraph.txt
    |   |-- ...
    |   `-- sff
    |-- K00002
    |   |-- 454AllContigs.fna
    |   |-- 454AllContigs.qual
    |   |-- 454ContigGraph.txt
    |   |-- ...
    |   `-- sff

=back

=head1 OPTIONS

=over 4

=item --contigs, -c

    the

=item --refseqKO, -r

    the prefix to which to append the KO id eg. /export2/home/uesu/db/konr/ko:

=item --threads, -t

    the number of threads to use

=item --prefix, -p

    the location for all the intermediate files

=item --help

    throws up the help message

=back

=cut

